services:
  app:
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: dev
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    env_file:
      - path: ./dev/.env
      - path: ./dev/override.env
        required: false
    volumes:
      - ../:/app
      - ../runtime:/app/runtime
      - logs_data:/app/runtime/logs
    tty: true

  web:
    ports:
      - "${DEV_PORT:-8080}:80"

  mysql:
    ports:
      - "${MYSQL_FORWARD_PORT:-3306}:3306"

  redis:
    ports:
      - "${REDIS_FORWARD_PORT:-6379}:6379"
