[program:queue-worker]
command=php /app/yii queue:work --sleep=3 --queue=mysql
directory=/app
process_name=%(program_name)s
autostart=true
autorestart=true
startsecs=3
numprocs=1
user=www-data
stdout_logfile=/app/runtime/logs/supervisor/queue-worker.stdout.log
stderr_logfile=/app/runtime/logs/supervisor/queue-worker.stderr.log
stopasgroup=true
killasgroup=true

